version: "3.7"
services:
  tensorflow:
    image: python38
    container_name: tensorflow
    command: bash
    volumes:
      - ./:/workdir/
  dashapp:
    image: dashapp
    container_name: dashapp
    build: 
      context: .
      dockerfile: Dockerfile-fix
      target: dashapp
    ports:
      - "8050:8050"
    links:
      - predapp
    # volumes:
    # command: python /workdir/app/dashboard.py
  predapp:
    image: predapp
    container_name: predapp
    build: 
      context: .
      dockerfile: Dockerfile-fix
      target: predapp
    ports:
      - "8080:8080"
    # volumes:
    # command: python /workdir/app/app.py

