version: "3.7"
services:
  dashapp:
    image: dashapp
    container_name: dashapp
    build: 
      context: .
      dockerfile: Dockerfile
      target: dashapp
    ports:
      - "8050:8050"
    links:
      - predapp
    volumes:
      - ./:/workdir/
    environment:
      - PREDAPP_IP
      - PREDAPP_PORT
  predapp:
    image: predapp
    container_name: predapp
    build: 
      context: .
      dockerfile: Dockerfile
      target: predapp
    ports:
      - "$PREDAPP_PORT:8080"
    volumes:
      - ./:/workdir/

